### ISSUE TITLE
How to exclude a certain path from gitbucket crawler

### ISSUE THREAD

**Issue by dracorp** [codelibs/gitbucket-fess-plugin#23]
Hello
I'm using gitbucket-fess-plugin to search in gitbucket repositories. How can I exclude certain catalogs, repositories, or groups from indexing/crawling?
Should I add a label to GitBucketCrawl? If yes how should I define the label?

URL to the GitBucket: http://git.domain.tld/ # #

**Comment by kw-udon** [comment]
Sorry for late response.
Though Fess's GitBucket crawler doesn't have such feature, you can exclude specific repositories by modifying their visibilities for a GitBucket user who generates a token for Fess in [Step 2](https://github.com/codelibs/gitbucket-fess-plugin/tree/6526ec8c7c883cf70816d14380ef6d5f6794e5f0#step-2-generate-token-for-crawler-gitbucket).
Since Fess's crawler will access each repository by using the token, it cannot access repositories that the GitBucket user cannot read.

**Comment by dracorp** [comment]
Hi
This is unfortunately not enough. I have too many repositories. But it's always a solution.
