### ISSUE TITLE
Compatibility with Gitbucket 4.31.x

### ISSUE THREAD

**Issue by jellykells** [codelibs/gitbucket-fess-plugin#26]
I'd really like to use this plugin with my GitBucket instance.  In the latest versions of GitBucket the Fess search page gives the following error

> Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: <!DOCTYPE html> ...

**Comment by kw-udon** [comment]
Thank you for reporting, but I couldn't reproduce this error. The latest plugin (v1.4.2) worked well with GitBucket 4.31.2 on my environment.

I'd like to see the full error message for this. Can you see more detailed error messages when you start GitBucket from your command line?

**Comment by jellykells** [comment]
v1.4.1 is the latest fess plugin release available. I did try building and using the v1.4.2 snapshot but got the same error.

I'll attach the full error text as a file.
[log.txt](https://github.com/codelibs/gitbucket-fess-plugin/files/3141901/log.txt)

**Comment by kw-udon** [comment]
Thank you for providing the log. It seems that Fess's URL was not properly set in GitBucket and the plugin failed to get JSON responses from Fess.

According to the log, I guess you added `http://<your Fess URL>/fess` as Fess's URL in [Step 5](https://github.com/codelibs/gitbucket-fess-plugin#step-5-register-fesss-url-gitbucket),  but you don't need `/fess`-suffix. 
So, could you try to change the Fess URL? It should be an address where the top page will be displayed when you access via a browser.

Note that the `/fess` suffix is used in README just because we used `-Dfess.context.path=/fess/` flag [in the example command](https://github.com/codelibs/gitbucket-fess-plugin#step-1-run-gitbucket-and-fess). Sorry for the confusing instruction. Let me add some extra explanation in README.

**Comment by jellykells** [comment]
I can't believe it was that simple. Thank you very much!

**Comment by kw-udon** [comment]
Great!

Let me change the title of this issue for future reference.
